services:
  db:
    image: 'postgres:latest'
    container_name: football-db
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
     - .env
    environment:
      - POSTGRES_USER=${FOOTBALL_USERNAME}
      - POSTGRES_PASSWORD=${FOOTBALL_PASSWORD}
      - POSTGRES_DB=${FOOTBALL_DATABASE}
    restart: unless-stopped
  web:
    image: 'football:1'
    container_name: football-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8088:3000'
    volumes:
      - .:/app
    env_file:
     - .env
    depends_on:
      - db
    restart: unless-stopped
volumes:
  postgres: 
