default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['PG_HOST'] %>
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>

test:
  <<: *default
  database: football_test

development:
  <<: *default
  database: <%= ENV['PG_DATABASE'] %>

production:
  <<: *default
  database: football_production
  username: <%= ENV['UNTITLEDAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['UNTITLEDAPP_DATABASE_PASSWORD'] %>
