default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: football
  password: 123123123

test:
  <<: *default
  database: football_test

development:
  <<: *default
  database: football_dev

production:
  <<: *default
  database: football_production
  username: <%= ENV['UNTITLEDAPP_DATABASE_USERNAME'] %>
  password: <%= ENV['UNTITLEDAPP_DATABASE_PASSWORD'] %>
