default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['PG_HOST'] %>
  database: <%= ENV['FOOTBALL_DATABASE'] %>
  username: <%= ENV['FOOTBALL_USERNAME'] %>
  password: <%= ENV['FOOTBALL_PASSWORD'] %>

test:
  <<: *default

development:
  <<: *default

production:
  <<: *default
